apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ddclient.configName" . }}
  labels:
    {{- include "ddclient.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.ddns }}
  ddclient.conf: >
    ssl={{ .ssl }}
    protocol={{ .protocol }}
    login={{ .login }}
    password={{ .password }}
    {{ .domain }}
    {{ .other }}
  {{- end }}